import * as React from "react";
import { createRoot } from "react-dom/client";

const { useMemo } = React;

const ICONS = {
  menu: "https://www.figma.com/api/mcp/asset/2f48414f-047f-4388-a462-297c51b04af6",
  people: "https://www.figma.com/api/mcp/asset/8e06817f-50bd-4adb-be11-4a9d3506180c",
  filter: "https://www.figma.com/api/mcp/asset/1fa82386-54c6-4d2d-bd1f-02aae1ca955e",
  thumb: "https://www.figma.com/api/mcp/asset/ddb064aa-c2c4-4065-be3f-893a2556accd",
  verified: "https://www.figma.com/api/mcp/asset/b80090eb-643a-40a8-bc2a-eb6d5a77a06e",
};

const css = `
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap');
*{box-sizing:border-box;margin:0;padding:0}
:root{--good:#c1ca85;--bad:#fa7d88;--neut:#bb93c2;--yellow:#ede280}
html,body,#root{width:100%;height:100%;min-height:100%}
body{font-family:Poppins,Arial,sans-serif;background:#f7f6f0;color:#282828;overflow:hidden}
button{font:inherit;color:inherit;background:none;border:0;cursor:pointer}
.page{width:100vw;height:100vh;display:flex;align-items:stretch;background:#f7f6f0;overflow:hidden}
.sidebar{width:259px;min-width:259px;flex:0 0 259px;height:100vh;background:#fff}
.main{flex:1 1 auto;min-width:0;height:100vh;display:flex;flex-direction:column;gap:8px}
.topbar{height:56px;flex:0 0 56px;width:100%;display:flex;align-items:center;justify-content:space-between;padding:0 8px}.menu{width:30px;height:30px}.menu img{width:30px;height:30px;display:block}.avatar-wrap{height:56px;padding:8px 16px;display:flex;align-items:center}.avatar{width:40px;height:40px;border-radius:200px;background:#aba698;color:#e9e8e0;display:grid;place-items:center;font-size:25px;font-weight:400;line-height:1}
.content{flex:1 1 auto;min-height:0;width:100%;padding:8px 32px 24px 24px;overflow:hidden}.stack{height:100%;min-height:0;width:100%;display:flex;flex-direction:column;gap:16px}.title-row{height:50px;flex:0 0 50px;display:flex;align-items:center;gap:16px}.back{width:40px;height:40px;flex:0 0 40px}.back img{width:40px;height:40px;display:block}.title{font-size:40px;font-weight:400;line-height:50px;white-space:nowrap;color:#282828}
.panel{flex:1 1 auto;min-height:0;width:100%;background:#fff;border-radius:8px 8px 0 0;padding:24px 0 16px;display:flex;flex-direction:column;gap:50px;overflow:hidden}.tabs-wrap{padding-left:16px;flex:0 0 auto}.tabs{height:48px;width:556px;display:flex;gap:16px;align-items:center}.tab{height:48px;position:relative;padding:0 8px;font-size:15px;font-weight:500;line-height:26px;letter-spacing:.46px;text-transform:uppercase;opacity:.7}.tab.active{opacity:1}.tab.active:after{content:"";position:absolute;left:0;right:0;bottom:0;height:2px;background:#282828}
.body{flex:1 1 auto;min-height:0;width:100%;display:flex;flex-direction:column;gap:40px}.stats{display:flex;gap:54px;align-items:center;padding:0 40px;flex:0 0 auto;overflow:hidden}.stat{display:flex;gap:16px;align-items:flex-start;flex:0 0 auto;overflow:hidden}.stat-icon{width:30px;height:30px;flex:0 0 30px;overflow:hidden}.stat-icon img{width:30px;height:30px;display:block}.stat-copy{display:flex;gap:16px;align-items:flex-end;color:#282828}.stat-value{font-size:50px;font-weight:400;line-height:.8;letter-spacing:-1px;white-space:nowrap}.stat-label{width:109px;font-size:16px;font-weight:400;line-height:1.3;color:#282828}
.grid{flex:1 1 auto;min-height:0;width:100%;padding:0 16px;display:flex;gap:16px;align-items:stretch;overflow:hidden}.flow-card{width:870px;flex:0 0 870px;background:#fbfaf9;border-radius:4px;padding:24px 0 24px 24px;display:flex;flex-direction:column;gap:24px;overflow:hidden}.kits{flex:1 1 auto;min-width:0;display:flex;flex-direction:column;gap:16px;justify-content:flex-start}.kit-card{height:340px;flex:0 0 340px;min-width:0;background:#fafaf9;border-radius:4px;padding:24px 24px 24px 0;display:flex;flex-direction:column;gap:24px;overflow:hidden}.card-title{height:50px;flex:0 0 50px;font-size:32px;font-weight:400;line-height:50px;color:#282828;white-space:nowrap}.kit-card .card-title{padding-left:40px}.chart{flex:1 1 auto;min-width:0;min-height:0;overflow:hidden;position:relative;background-image:radial-gradient(rgba(40,40,40,.08) 1px,transparent 1px);background-size:16px 16px}.stage{position:relative;width:100%;height:100%;overflow:hidden}.inner{position:relative;height:100%;min-width:var(--w)}.svg{position:absolute;inset:0;width:var(--w);height:var(--h);overflow:visible;pointer-events:none}.node{position:absolute;border-radius:0;outline:1px solid rgba(0,0,0,.04)}.node.good{background:#c1ca85}.node.bad{background:#fa7d88}.node.neut{background:#bb93c2}.node.yellow{background:#ede280}.label{position:absolute;top:50%;transform:translateY(-50%);font-size:12px;line-height:1.2;color:#111827;white-space:nowrap;text-decoration:underline;text-underline-offset:2px}.label.left{right:calc(100% + 10px);text-align:right}.label.right{left:calc(100% + 10px);text-align:left}.label b{font-weight:700}.step{position:absolute;top:0;transform:translateX(-50%);font-size:14px;font-weight:500;line-height:1.2;color:#111827;white-space:nowrap;text-align:center;z-index:2}
`;

const P = { w:844,h:678,scale:6.42,stepGap:146,left:0,top:30,nodeW:16,gap:18,steps:["Registered","El. Quiz","El. Filter","Confirm","E-Signature","Shipping Det."],nodes:[["registered",0,"Completed",100,"good","right"],["quiz_completed",1,"Completed",53,"good"],["quiz_pending",1,"Pending",12,"neut"],["quiz_abandoned",1,"Abandoned",35,"bad"],["filter_in",2,"Filtered In",39,"good"],["filter_out",2,"Filtered Out",10,"bad"],["confirmed",3,"Confirmed",13,"good"],["rejected",3,"Rejected",24,"bad"],["signed",4,"Signed",10,"good"],["esign_pending",4,"Pending",1,"neut"],["declined",4,"Declined",1,"bad"],["esign_abandoned",4,"Abandoned",1,"bad"],["provided",5,"Provided",8,"good"],["ship_abandoned",5,"Abandoned",1,"bad"]],links:[["registered","quiz_completed",53,"good"],["registered","quiz_pending",12,"neut"],["registered","quiz_abandoned",35,"bad"],["quiz_completed","filter_in",39,"good"],["quiz_completed","filter_out",10,"bad"],["filter_in","confirmed",13,"good"],["filter_in","rejected",24,"bad"],["confirmed","signed",10,"good"],["confirmed","esign_pending",1,"neut"],["confirmed","declined",1,"bad"],["confirmed","esign_abandoned",1,"bad"],["signed","provided",8,"good"],["signed","ship_abandoned",1,"bad"]]};
const K = { w:1022,h:221,scale:17,stepGap:136.5,left:120,top:32.5,nodeW:17,gap:14,steps:["Kit activated","Quiz completed","Data arrived","Report generated","Report approved","Report released","Report seen"],nodes:[["activated",0,"Activated",8,"good"],["completed",1,"Completed",7,"good"],["both",2,"Both",6,"good"],["bacteria",2,"Only bacteria",1,"neut"],["fungi",2,"Only fungi",1,"neut"],["generated",3,"Generated",4,"yellow"],["approved",4,"Approved",3,"yellow"],["released",5,"Released",2,"yellow"],["seen",6,"Seen",2,"yellow"]],links:[["activated","completed",7,"good"],["completed","both",6,"good"],["completed","bacteria",1,"neut"],["completed","fungi",1,"neut"],["both","generated",4,"yellow"],["generated","approved",3,"yellow"],["approved","released",2,"yellow"],["released","seen",2,"yellow"]]};

function build(cfg){const map={};cfg.steps.forEach((_,s)=>{let y=cfg.top;cfg.nodes.filter(n=>n[1]===s).forEach(n=>{const h=n[3]*cfg.scale;map[n[0]]={id:n[0],step:n[1],label:n[2],value:n[3],type:n[4],side:n[5],x:cfg.left+s*cfg.stepGap,y,w:cfg.nodeW,h};y+=h+cfg.gap})});const out={},inn={};const paths=cfg.links.map(l=>{const a=map[l[0]],b=map[l[1]],sw=l[2]*cfg.scale,ao=out[l[0]]||0,bo=inn[l[1]]||0;out[l[0]]=ao+sw;inn[l[1]]=bo+sw;const x1=a.x+a.w,y1=a.y+ao+sw/2,x2=b.x,y2=b.y+bo+sw/2,mx=(x1+x2)/2;return{d:`M${x1} ${y1} C${mx} ${y1},${mx} ${y2},${x2} ${y2}`,sw,type:l[3]}});return{nodes:Object.values(map),paths}}
function Sankey({cfg}){const data=useMemo(()=>build(cfg),[cfg]);return <div className="stage" style={{"--w":`${cfg.w}px`,"--h":`${cfg.h}px`}}><div className="inner"><svg className="svg" width={cfg.w} height={cfg.h} viewBox={`0 0 ${cfg.w} ${cfg.h}`}>{data.paths.map((p,i)=><path key={i} d={p.d} fill="none" stroke={`var(--${p.type})`} strokeWidth={p.sw} strokeLinecap="butt" opacity="0.62" />)}</svg>{cfg.steps.map((s,i)=><div className="step" key={s} style={{left:cfg.left+i*cfg.stepGap+cfg.nodeW/2}}>{s}</div>)}{data.nodes.map(n=><div className={`node ${n.type}`} key={n.id} style={{left:n.x,top:n.y,width:n.w,height:n.h}}>{n.step!==0&&<div className={`label ${n.side||"left"}`}>{n.label} (<b>{n.value}</b>)</div>}</div>)}</div></div>}
function Stat({src,value,lines}){return <div className="stat"><div className="stat-icon"><img src={src} alt="" /></div><div className="stat-copy"><div className="stat-value">{value}</div><div className="stat-label">{lines.map(x=><React.Fragment key={x}>{x}<br/></React.Fragment>)}</div></div></div>}
function App(){return <><style>{css}</style><div className="page"><aside className="sidebar"/><main className="main"><header className="topbar"><button className="menu"><img src={ICONS.menu} alt=""/></button><div className="avatar-wrap"><div className="avatar">A</div></div></header><section className="content"><div className="stack"><div className="title-row"><button className="back"><img src="/NavigateBeforeFilled.svg" alt="Back"/></button><h1 className="title">Lorem Ipsum</h1></div><div className="panel"><div className="tabs-wrap"><nav className="tabs"><button className="tab active">Dashboard</button><button className="tab">Participants</button><button className="tab">Settings</button></nav></div><div className="body"><div className="stats"><Stat src={ICONS.people} value="126" lines={["Total","Participants"]}/><Stat src={ICONS.filter} value="13" lines={["Filtered In","Participants"]}/><Stat src={ICONS.thumb} value="10" lines={["Confirmed","Participants"]}/><Stat src={ICONS.verified} value="3" lines={["Completed","Tests"]}/></div><div className="grid"><section className="flow-card"><h2 className="card-title">Participant flow</h2><div className="chart"><Sankey cfg={P}/></div></section><div className="kits"><section className="kit-card"><h2 className="card-title">Kit #1</h2><div className="chart"><Sankey cfg={K}/></div></section><section className="kit-card"><h2 className="card-title">Kit #2</h2><div className="chart"><Sankey cfg={K}/></div></section></div></div></div></div></div></section></main></div></>}

createRoot(document.getElementById("root")).render(<App/>);